### ISSUE TITLE
Cannot find module '@tsed/cli-plugin-eslint'

### ISSUE THREAD

**Issue by lucasmtav** [TypedProject/tsed-cli#104]
I'm using node v14.16.0 with NVM, and I can't run any cli command, they all point out an error in the module "@tsed/cli-plugin-eslint"

![image](https://user-images.githubusercontent.com/11954168/113637547-37559000-964b-11eb-883d-662752620c54.png)

**Comment by lucasmtav** [comment]
I ran the command "npm uninstall tsed" apparently solved the problem

**Comment by Romakita** [comment]
ok ^^
