### ISSUE TITLE
unable to init project

### ISSUE THREAD

**Issue by old-suyash-kale** [TypedProject/tsed-cli#108]
![Screenshot 2021-04-14 at 6 20 23 PM](https://user-images.githubusercontent.com/15926942/114712983-4b397a00-9d4e-11eb-8a81-c6d9a6857da5.png)

**Comment by antonio-piha** [comment]
Install latest version of tsed/cli which works and try again:
```
npm install -g @tsed/cli@2.13.2
tsed init .
```

**Comment by Romakita** [comment]
Fixed with the latest version v3.0.3
