### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by polarisdigitech** [TypedProject/tsed-cli#34]
Been having issues creating a new project with the cli. It's always stuck on

![Capture 1](https://user-images.githubusercontent.com/47317964/97968409-835b8a80-1db6-11eb-8b9d-d906d4e83c17.PNG)

And this, sometimes

![Capture 2](https://user-images.githubusercontent.com/47317964/97968484-98d0b480-1db6-11eb-8338-d18065d0bf2c.PNG)

Any ideas why this is happening and how I can get past this.

**Comment by Romakita** [comment]
Hello @polarisdigitech 
The cli works as expected. ECONRESET means that your connection use a proxy or somethings which block the connection.
I can't help you about proxy issue unfortunatly. It depends on your proxy configuration.

See you

**Comment by Romakita** [comment]
Try the same command with --verbose option to more details :)

**Comment by polarisdigitech** [comment]
> Hello @polarisdigitech
> The cli works as expected. ECONRESET means that your connection use a proxy or somethings which block the connection.
> I can't help you about proxy issue unfortunatly. It depends on your proxy configuration.
> 
> See you

I've tried it on my home and work networks. I can understand the first, but I get the second issue on my home network
