### ISSUE TITLE
Stuck in the "resolve versions" step when GraphQL feature is selected

### ISSUE THREAD

**Issue by d-corler** [TypedProject/tsed-cli#37]
When I create a project and select the feature "**GraphQL**", the packages resolution never ends.

Example of configuration :
- _Choose the target platform_: **Koa.js**
- _Check the features needed for your project_:
  - ✅  GraphQL ← _**Seems to be the culprit**_ 👨‍⚖️
  - ✅  Database
  - ✅ Passport.js
  - ✅ Socket.io
  - 🔲 Swagger
  - ✅ Testing
  - ✅ Linter
- _Choose a ORM manager_: **Mongoose**
- _Choose unit framework_: **Jest**
- _Choose linter tools framework_: **EsLint**
- _Choose extra linter tools_:
  - ✅ Prettier
  - ✅ Lint on commit

![image](https://user-images.githubusercontent.com/31737627/98358228-ac825200-2026-11eb-9c97-6a3a8d96329a.png)

**Comment by Romakita** [comment]
Hello @d-corler 
I'll fix this problem ;)
See you

**Comment by Romakita** [comment]
Hello @d-corler 
I'm not able to reproduce the issue. The install have been done correctly. 
Can you retry?
Romain

**Comment by d-corler** [comment]
Hi @Romakita

This problem seems to have a random behavior, here are the results of my experiments (in order) :

- [PWS] Express + GraphQl : ✔️ works
- [PWS] Koa + GraphQl : ❌ stuck at "[35/36] Resolving packages..."
- [CMD] Express + GraphQl : ✔️ works
- [CMD] Koa + GraphQl : ❌ stuck at "[34/36] Resolving packages..."
- [PWS] Express + GraphQl : ❌ stuck at "[34/35] Resolving packages..."
- [PWS] Koa + GraphQl : ❌ stuck at "[33/36] Resolving packages..."
- [PWS] Express + GraphQl : ❌ stuck at "[33/35] Resolving packages..."

> PWSH : Powershell 5.1.19041.546 (embedded into _Windows Terminal App_ 1.3.2651.0)
> CMD : Terminal 10.0.19041.572

Each time I waited at least 20 minutes to be sure the process didn't continue.

---
My environment :
- Windows : 2004 (19041.572)
- Yarn : 1.22.5
- Node : 14.13.0

---
**BUT** I tried with WSL (v2, Debian 10), and everything works perfectly 🤔

**Comment by Romakita** [comment]
Hello @d-corler 
I haven't windows, so I'm not able to fix this issue. 

The post install isn't really important, until the files are correctly generated in the project. You can kill the process and run yarn or npm manually with --verbose option to see what is wrong.

I deployed a new release on NPM which add --verbose option on yarn / npm commands executed by the cli. It should give you more detail on the problem :) 

See you
Romain

**Comment by d-corler** [comment]
Hi @Romakita 

Files aren't yet generated when the problem occurs, and I cannot kill the process, I need to close the entire terminal (thread blocked ?).

**Comment by Romakita** [comment]
I don't know ^^. I'm not able to reproduce the issue. Have you tried with the latest version. I added verbose flag on npm/yarn install. You should have more details.

**Comment by Romakita** [comment]
Maybe we can organize an hangout to find the reason of this problem :) Tell me if you are interested ;)

**Comment by d-corler** [comment]
Yep I tried with the latest version, but no more outputs.

Over the next few days I'm going to explore the code to understand what may be the problem, I keep you informed. An hangout sounds a good idea if I found nothing or if I'm struggled.

**Comment by Romakita** [comment]
Ok :) 
Don't hesitate ;)
