### ISSUE TITLE
Check for yarn & install

### ISSUE THREAD

**Issue by bpofficial** [TypedProject/tsed-cli#5]
Hi just a quick tip I suppose. Upon running `tsed init .` without yarn installed the installer will crash as yarn isn't installed. I suppose it would be smoother to install yarn if it is not installed already to mitigate this.

**Comment by Romakita** [comment]
ha yes the init doesn't check correctly the yarn availability.

**Comment by Romakita** [comment]
Fixed :)

Now to reinstall CLI, you don't need to put @beta 

Just use:
```
npm install -g @tsed/cli
```

**Comment by Romakita** [comment]
I prefer to use the prefered package manager. So I just check if yarn exist then fallback to npm :)
