### ISSUE TITLE
[FEAT] Add ResponseFilter template

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed-cli#67]
## Information

As developer I want to generate a ResponseFilter described here:
https://tsed.io/docs/response-filter.html

<img width="228" alt="Capture d’écran 2021-01-30 à 13 41 50" src="https://user-images.githubusercontent.com/1763311/106356593-1eee8f80-6301-11eb-97c0-a37bf378bfb6.png">

## Steps

- [x] Create new entry here: https://github.com/TypedProject/tsed-cli/blob/master/packages/cli/src/commands/generate/ProviderTypes.ts
- [x] Create new hbs template response-filter.hbs (https://github.com/TypedProject/tsed-cli/tree/master/packages/cli/templates/generate)
- [x] Create new integration test (https://github.com/TypedProject/tsed-cli/blob/master/packages/cli/test/integrations/generate/generate.exception-filter.integration.spec.ts)

## Acceptance criteria

- [x] The template is correctly generated

**Comment by flexwie** [comment]
implemented in #68
