### ISSUE TITLE
Multi typeorm

### ISSUE THREAD

**Issue by d0whc3r** [TypedProject/tsed-cli#7]
It could be a good stuff to have multiple database generation in init command, or maybe 2, one for development and other for production like jhipster generator

![image](https://user-images.githubusercontent.com/1378986/81041477-37cf2f00-8eae-11ea-98d5-212dbf0dad76.png)

https://start.jhipster.tech/#/generate-application

**Comment by Romakita** [comment]
It's a redundant with `tsed generate` no ? And I'd just use the official typeorm cli to generate file.
There is many way to change the connection in dev or production. 

For example, I use environment variable to change the database connection (not the type I agree).

I think add this options is too much. Developer just have to use `tsed generate` command to create another connection :)
