### ISSUE TITLE
Documentation regarding extend Cli for custom command

### ISSUE THREAD

**Issue by tlfbrito** [TypedProject/tsed-cli#91]
Is it possible to use tsed-cli to create CLI command for an existing tsed project?
From the documentation that doesn't seem obvious, I think it would be good if that could be clarified, because it might be useful for people that want to use the Framework with CLI commands.

Thanks

**Comment by Romakita** [comment]
Hello @tlfbrito 
> Is it possible to use tsed-cli to create CLI command for an existing tsed project?
I don't understand.
You want to create a new command like the @tsed/cli-jest-plugin ?

**Comment by tlfbrito** [comment]
I would like to be able to create my own commands in an existing tsed application.
I don't want to create a library or a plugin to share among other projects, the objective would be create commands/console to be used in the application. (eg: command to consume from a queue)

**Comment by Romakita** [comment]
The CLI is not design to do that originally but, I think it’s possible. 

Is it possible to describe a usecase/userstory and maybe a small example usage?
Please.

**Comment by tlfbrito** [comment]
**Example 1:**

> As a developer, I want to be able to create console commands to consume queues (eg: AWS SQS or Rabbit MQ) and control the cadency of consumption.

**Example 2:**
> As a developer, I want to be able to create console commands to be executed in a CRON to create a scheduled report (eg: csv, XML) on background.

This idea comes from:
https://symfony.com/doc/current/console.html
https://github.com/Pop-Code/nestjs-console

@Romakita , let me know if this is ok, or if you need anything else.

**Comment by Romakita** [comment]
Ok I see. 

To clarify the needs, you want to be able to run command from the tsed cli:
```sh
tsed run mycmdapp
```
And run your code. Actually, there is one limitation important limitation. The CLI is already compiled in js, so It won't be able to run the typescript code. So I need to use ts-node. 

A temporary solution is to use the npm run command as it's explained in the nestjs-console:

```
{
    "scripts": {
        // from sources
        "console:dev": "cross-env NODE_ENV=development ts-node -r tsconfig-paths/register src/console.ts",
        // from build (we suppose your app was built in the dist folder)
        "console": "cross-env NODE_ENV=production node dist/console.js"
    }
}
```
Here is the steps to do that.

### Create the src/console.ts

```typescript
#!/usr/bin/env node
import {Cli} from "@tsed/cli-core";
import {impo} from "@tsed/cli-core";
import {resolve} from "path";

const pkg = require("../../package.json");

async function bootstrap() {
  const cli = await Cli.bootstrap({
    name: "tsed", // the name of you custom CLI
    pkg,
    commands: [
        // add class decorated with @Command here
    ]
  });

  cli.parseArgs();
}

bootstrap();
```
Then, you can create a command and inject service:

```typescript
import {createTasks} from "@tsed/cli-core";
export interface MyCmdContext {
  argName: string;
  version: string;
}

@Command({
  name: "do",
  description: "Do something",
  args: {
    argName: {
      type: String,
      defaultValue: "default",
      description: "My Arg"
    }
  },
  options: {
    "--version <version>": {
      type: String,
      description: "Use a specific version of Ts.ED (format: 5.x.x)"
    }
  }
})
export class MyCmd implements CommandProvider {
  @Inject()
  myService: MyService;
  /**
   *  Ask questions with Inquirer. Return an empty array or don't implement the method to skip this step
   */
  async $prompt(initialOptions: Partial<MyCmdContext>): Promise<QuestionOptions> {
  
    return [
      {
        type: "list",
        name: "version",
        message: "Select a Ts.ED version",
        default: initialOptions.version,
        when: !initialOptions.version,
        choices: versions
      }
    ];
  }
  /**
   * This method is called after the $prompt to create / map inputs to a proper context for the next step 
   */
  $mapContext(ctx: Partial<MyCmdContext>): MyCmdContext {
      return {
         ...ctx,
         // map something, based on ctx
      }
  }
 /**
  *  This step run your tasks with Listr module
  */
  async $exec(ctx: InitCmdContext): Promise<any> {
    return [
       {
          title: "Do something",
          task: (ctx: any) => {
             return this.myService.doSomething() // Note: Listr support Promise and Observable :)
          }
       },
       { // tasks with subtask
        title: "Run task with subtasks",
        task: (ctx: any) => {
          return createTasks(
            [
              {
                title: "Root files",
                task: () => (/*...*/)
               }
           ]
       }
    ];
  }
}
```
If you have any question, tell me. This issue will be the good entry point to create a good documentation on the website ;). So your question/feedback are welcome!

See you
Romain

**Comment by Romakita** [comment]
For the CLI enhancement:

The expected solution will be:
```
{
    "scripts": {
        // from sources
        "console:dev": "tsed run do something --development",
        // from build (we suppose your app was built in the dist folder)
       // by default root will be ./dist and can be omitted 
        "console": "tsed run do something --production --root=./dist" 
    }
}
```
By convention, Ts.ED will import the bin/index.ts `./src/bin/index.ts` in development mode and `./dist/bin/index.js` in production mode.

The `bin/index.ts` will export all commands (draft):
```typescript
import {MyCommand} from "../MyCommand";
 
export default  [
   MyCommand
]
```
The bootstrap function will be managed by the `@tsed/cli-core` (if it's possible).

**Comment by tlfbrito** [comment]
> Ok I see.
> 
> To clarify the needs, you want to be able to run command from the tsed cli:
> 
> ```shell
> tsed run mycmdapp
> ```
> 
> And run your code. Actually, there is one important limitation. The CLI is already compiled in js, so It won't be able to run the typescript code. So I need to use ts-node as dependency to do that in future.
> 
> A temporary solution is to use the npm run command as it's explained in the nestjs-console:
> 
> ```
> {
>     "scripts": {
>         // from sources
>         "console:dev": "cross-env NODE_ENV=development ts-node -r tsconfig-paths/register src/console.ts",
>         // from build (we suppose your app was built in the dist folder)
>         "console": "cross-env NODE_ENV=production node dist/console.js"
>     }
> }
> ```
> 
> usage:
> 
> ```
> npm run console:dev -- do --version
> yarn console:dev do --version
> ```
> 
> Here is the steps to do that.
> 
> ### Create the src/console.ts
> ```ts
> #!/usr/bin/env node
> import {Cli} from "@tsed/cli-core";
> import {impo} from "@tsed/cli-core";
> import {resolve} from "path";
> 
> const pkg = require("../../package.json");
> 
> async function bootstrap() {
>   const cli = await Cli.bootstrap({
>     name: "tsed", // the name of you custom CLI
>     pkg,
>     commands: [
>         // add class decorated with @Command here
>     ]
>   });
> 
>   cli.parseArgs();
> }
> 
> bootstrap();
> ```
> 
> Then, you can create a command and inject service:
> 
> ```ts
> import {createTasks, Command, QuestionOptions, CommandProvider} from "@tsed/cli-core";
> import {Inject} from "@tsed/di";
> 
> export interface MyCmdContext {
>   argName: string;
>   version: string;
> }
> 
> @Command({
>   name: "do",
>   description: "Do something",
>   args: {
>     argName: {
>       type: String,
>       defaultValue: "default",
>       description: "My Arg"
>     }
>   },
>   options: {
>     "--version <version>": {
>       type: String,
>       description: "Use a specific version of Ts.ED (format: 5.x.x)"
>     }
>   }
> })
> export class MyCmd implements CommandProvider {
>   @Inject()
>   myService: MyService;
>   /**
>    *  Ask questions with Inquirer. Return an empty array or don't implement the method to skip this step
>    */
>   async $prompt(initialOptions: Partial<MyCmdContext>): Promise<QuestionOptions> {
>   
>     return [
>       {
>         type: "list",
>         name: "version",
>         message: "Select a Ts.ED version",
>         default: initialOptions.version,
>         when: !initialOptions.version,
>         choices: versions
>       }
>     ];
>   }
>   /**
>    * This method is called after the $prompt to create / map inputs to a proper context for the next step 
>    */
>   $mapContext(ctx: Partial<MyCmdContext>): MyCmdContext {
>       return {
>          ...ctx,
>          // map something, based on ctx
>       }
>   }
>  /**
>   *  This step run your tasks with Listr module
>   */
>   async $exec(ctx: InitCmdContext): Promise<any> {
>     return [
>        {
>           title: "Do something",
>           task: (ctx: any) => {
>              return this.myService.doSomething() // Note: Listr support Promise and Observable :)
>           }
>        },
>        { // tasks with subtask
>         title: "Run task with subtasks",
>         task: (ctx: any) => {
>           return createTasks(
>             [
>               {
>                 title: "Root files",
>                 task: () => (/*...*/)
>                }
>            ]
>        }
>     ];
>   }
> }
> ```
> 
> If you have any question, tell me. This issue will be the good entry point to create a good documentation on the website ;). So your question/feedback are welcome!
> 
> See you
> Romain

I tried this, I think this is similar to what is in the `@tsed/cli-core` documentation also, but I always get this error:

```bash
npm run console:dev -- do --version

> tsed-demo@1.0.0 console:dev /Users/TiagoBrito/Sites/tsed-demo
> cross-env NODE_ENV=development ts-node -r tsconfig-paths/register src/console.ts "do" "--version"

Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
Error: Cannot find module '../../package.json'
```
if I change the `const pkg = require("../../package.json");` to match my `package.json` path: `const pkg = require("../package.json");`, I get another error:

```bash
npm run console:dev -- do --version

> tsed-demo@1.0.0 console:dev /Users/TiagoBrito/Sites/tsed-demo
> cross-env NODE_ENV=development ts-node -r tsconfig-paths/register src/console.ts "do" "--version"

Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
(node:90172) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tsed-demo'
```

I think it's because https://github.com/TypedProject/tsed-cli/blob/master/packages/cli-core/src/Cli.ts#L66, but probably I'm doing something wrong.


Thanks for your help.

**Comment by Romakita** [comment]
Ok I'll investigate. I'll try to create a repo example ;)

**Comment by Romakita** [comment]
Hello @tlfbrito 
I worked on a new CLI version to allow this new usage. You can test it right know.

Install the CLI: `npm i -g @tsed/cli@3.0.0-rc.3`

You can also checkout the example here: https://github.com/Romakita/tsed-example-commands

The RC3 allow to run a project command directly from the CLI:  `tsed run hello`

It works as expected :)

**Comment by tlfbrito** [comment]
Thanks @Romakita it works!

This was exactly what I was looking for. Thanks!

**Comment by Romakita** [comment]
Good news! I’ll try finish the work on the cli v3 ;)

**Comment by Romakita** [comment]
CLI v3 is released :)
